migration_level: 20
general:
  displayName: steak_lol
  language: en-US
  keybindings:
    search:
      - ctrlKey
      - KeyF
    home:
      - ctrlKey
      - KeyH
    listenNow:
      - ctrlKey
      - KeyL
    browse:
      - ctrlKey
      - KeyN
    recentlyAdded:
      - ctrlKey
      - Digit1
    librarySongs:
      - ctrlKey
      - Digit2
    libraryAlbums:
      - ctrlKey
      - Digit3
    libraryArtists:
      - ctrlKey
      - Digit4
    immersiveMode:
      - ctrlKey
      - KeyP
    commandCenter:
      - shiftKey
      - Space
    miniPlayer:
      - ctrlKey
      - KeyK
  collapsedItems: []
  closeToTray: false
  promptOnClose: false
  warnBeforeQueueOverride: false
  startupPage: /am/home
  checkForMarketplaceUpdates: true
  checkForUpdates: true
audio:
  volume: 1
  volumeStep: 0.01
  exponentialVolume: true
  maxVolume: 1
  volumeDisplaySPL:
    enabled: false
    calibration: 90
  equalizer:
    enabled: false
    preset: default
    frequencies:
      - 32
      - 63
      - 125
      - 250
      - 500
      - 1000
      - 2000
      - 4000
      - 8000
      - 16000
    gain:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
    Q:
      - 0.707
      - 0.707
      - 0.707
      - 0.707
      - 0.707
      - 0.707
      - 0.707
      - 0.707
      - 0.707
      - 0.707
    mix: 1
    vibrantBass: 0
    userGenerated: false
  showBitrateBadge: false
  ciderAudio:
    enabled: false
    showInToolbar: false
    showBadges: true
    ciderPPE: true
    ciderPPE_value: MAIKIWI
    staticOptimizer:
      state: false
      lock: false
    lastNode: n1
    firstNode: spatial
    opportunisticCorrection_state: OFF
    atmosphereRealizer1: false
    atmosphereRealizer1_value: NATURAL_STANDARD
    atmosphereRealizer2: false
    atmosphereRealizer2_value: Z3600
    spatial: false
    spatialProfile: maikiwinewer
  normalization: false
  podcastsPlaybackSpeed: 1
  allowPlaybackRateChangeEverywhere: false
visual:
  appearance: dark
  layoutType: default
  layoutView: HHh LpR FFf
  useAdaptiveColors: true
  useEmotionEngine: true
  adaptiveColorPercent: 10
  viewTransitions: true
  prefersReducedMotion: false
  windowSize:
    - 1024
    - 640
  windowPosition:
    - 0
    - 0
  titleBarStyle: default
  artworkLoadingMethod: lazy
  artworkBlurMap:
    fpsLimit: 60
  backgroundBlurMap:
    enabled: false
    src: ""
    filter:
      blur: 128
      saturate: 200
      brightness: 10
      contrast: 100
  immersive:
    useAnimatedBackground: true
    useAnimatedArtwork: true
    backgroundType: default
    layoutType: solarium
    layoutTypePortrait: sonoma
    maxBackgroundBrightness: 50
    useBackgroundBPM: true
    startFullscreen: false
    filter:
      saturate: 180
      contrast: 1.3
  customCSS: ""
  lyricSpeedMultiplier: 1
  scalingFactor: 1
  fonts:
    main: Figtree
    lyrics: Figtree
  overlayDrawer: false
  scrollbarType: native
  vibrancyMode: mica
  acrylicDarkValue: 0.5
  hiresImages: false
  pauseAnimatedOnBlur: true
  sweetener:
    useImmersiveBG: true
    immersiveBGStyle: default
    immersive_bg_fps: 30
    immersive_lower_fps_on_blur: true
    immersive_bg_filter:
      blur: 128
      saturate: 100
      brightness: 40
      contrast: 95
  ui_custom:
    useSystemAccentColor: false
    customAccentColor: false
    customAccentColorValue: "#fa2d48"
    customTintColor: false
    customTintColorValue: "#fa2d48"
    customTintColorRatio: 0.5
  ultraWide: false
  sizing: default
  transparency: true
ui:
  chromeTopWidget: search
  leftDrawerOverlay: false
  windowControlOverride: default
  mainMenuPosition: left
  forceMPWindowControls: false
components:
  SidebarPlaylist:
    ShowArtwork: true
  PlaylistTimeMachine:
    maxEntries: 10
  Search:
    SearchType: default
  FloatingSearch:
    EnterShowsResults: true
    BlurBackground: true
    ClearSearchOnClose: false
  AddToPlaylist:
    RecentsLimit: 3
  AMProgressBar:
    iOSStyle: true
    useAccentColor: false
  AMVolumeSlider:
    iOSStyle: false
  HeaderSearch:
    NoRedirectOnSelect: false
  ImmersiveSonoma:
    UseRadialMask: true
  ImmersiveSolarium:
    MaskType: radial
    LyricsType: full
    AspectRatio: 4/3
    QueueIsDrawer: true
    MaskYPosition: 50
  Immersive:
    StartTab: queue
    MaxLyricSize: 70
    KeepCompletedLyrics: false
    ControlsTimeout: 1
    ArtworkHighlight: true
    HideSidePanelWhenNoLyrics: true
    EnableTransparency: false
    TransparencyValue: 1
    CustomImagePath: ""
    CustomImageFilter:
      blur: 0
      saturate: 100
      brightness: 100
      contrast: 100
    CustomImageMixValue: 0.5
    GlowEffectOnActiveLyrics: true
  SimpleImmersiveBGArtwork:
    UseMask: true
    filter:
      blur: 0
      saturate: 280
      brightness: 50
      contrast: 100
  MediaItem:
    AnimateArtworkOnHover: false
  MediaItemArtwork:
    DisableFadeIn: false
    Highlights: true
  HLSVideo:
    NVFix: false
  PlaylistsPage:
    iOSLayout: false
    iOSLayoutAlways: false
    editorialLayout: false
    editorialPreference:
      - bannerUber
      - storeFlowcase
      - subscriptionHero
      - originalFlowcaseBrick
  CompactSidebar:
    size: small
    align: top
  Window:
    TitleBarControlSize: large
  ListItemProvider:
    fetchAttributes: true
  MiniPlayer:
    AnimatedArtwork: false
    allowResizing: true
  MojaveLayouts:
    PlayerType: glass
    ShowQuickActions: true
  AMPLCD:
    Style: glass
  RichAlbumGrid:
    ScrollToPosition: top
    DisableScrollAnimation: false
    AlwaysNavigateToPage: false
  ThreeDQueue:
    Style: default
  SidebarProfile:
    Enabled: true
    HasMainMenu: false
    HandleVisible: false
    NameVisible: true
  ImmersiveSingAlong:
    CustomCSS: >
      .lyric_fade-enter-active {
        transition: 0.5s var(--ease_smoothEase), opacity 1s var(--ease_smoothEase),
          transform 1s var(--ease_smoothEase), filter 0.36s var(--ease_smoothEase) !important;
      }

      .lyric_fade-leave-active {
        transition: 0.5s var(--ease_smoothEase), opacity 0.5s var(--ease_smoothEase),
          transform 1s var(--ease_smoothEase), filter 0.5s var(--ease_smoothEase) !important;
      }

      .lyric_fade-enter-from {
        opacity: 0;
        transform: translateY(25%) perspective(300px) translateZ(-50px) !important;
        filter: blur(10px);
      }

      .lyric_fade-leave-to {
        opacity: 0;
        transform: translateY(-25%) perspective(300px) translateZ(-50px) rotateX(0deg) !important;
        filter: blur(10px);
      }
    CustomCSSEnabled: false
    PlayerIdleBehavior: hide
caching:
  LibraryAlbums: true
  Content: true
  ArtistChips: true
  Home: true
lyrics:
  timeOffset: 0
  thirdPartySources: true
  scaleOnAny: false
  characterFlow: true
  lineStaggering: true
  lineStaggeringImmersive: true
  singLyricsEverywhere: false
  translationEnabled: false
  translationLanguage: en
  style:
    enabled: false
    easingFunction: ""
    easingFunctionImmersive: ""
    duration: 0.5
    durationImmersive: 1
advanced:
  flags: []
  disableLogging: false
  enableMediaItemInspect: true
  disableLargeRequestOffloading: true
  testing:
    musicVideos: true
    forceExplicit: true
    floatingSearch: false
connectivity:
  playbackNotifications: true
  playbackNotificationType: native
  webSockets:
    enabled: true
  apiTokensRequired: true
  apiTokens: []
  discord:
    enabled: true
    client: AppleMusic
    clearOnPause: true
    stateFormat: by {artist}
    detailsFormat: "{title}"
    timestampFormat: remaining
    buttons:
      - songLink
      - appleMusicLink
    useAnimatedArtwork: false
    showAlbum: true
    showArtist: true
    showMultipleArtists: true
    smallImage: artists
    largeImage: animated
  lastfm:
    loggedIn: false
    username: ""
    settings:
      removeFeat: both
      scrobbleDelay: "50"
      removeExtension: false
  atmosRatings:
    enabled: true
appleMusic:
  enabled: true
  drmSystem: default
  privateEnabled: false
  animatedArtwork: true
  catalogAnimatedArtwork: false
  animatedArtworkLevel: -1
  showUserInfo: true
  seamlessAudioTransitions: true
  showStorefrontWarning: true
  popularityThreshold: 0.6
  backgroundRefreshTime: 60
  showBPM: false
  language: auto
  storefront: auto
  noPlayingAction: play-recent-tracks
  lyrics:
    singLyrics: true
    staticLyrics: false
  libraryAlbums:
    sortBy: name
    order: asc
  librarySongs:
    sortBy: none
    order: desc
    showArtwork: false
    queueLimit: 150
    itemSize: default
  libraryPlaylists:
    sortBy: none
    order: asc
  home:
    pinnedItems: []
    pinnedItemsViewType: list
    sectionsOrder:
      - pinnedItems
      - recentlyPlayed
      - artistFeed
      - moodRecommendations
      - madeForYou
      - fromShazam
      - friendsListeningTo
    followedArtists: []
    buttonLocation: sidebar
    lastSelectedMood: Feel Good
    artwork:
      enabled: false
      url: ""
      video: false
      position: center
  browse:
    hideHeroItems: false
    moveUpLinks: false
  useAMPComponents: {}
  podcasts:
    following: []
casting:
  enabled: false
remote:
  enabled: false
  autostartTunnel: true
  tunnelUUID: ""
updates:
  updateChannel: stable
  checkForUpdates: true
DVTCfg: {}
plugins:
  me.thebroz.better-visualizer:
    visualizerDampening: 0.45
    visualizerColoring: cider-red
